const express = require("express"),
      helpers = require("../helpers/todos");
      router  = express.Router(),
      db      = require("../models");

router.route("/")
.get(helpers.getTodos)
/**
 * @api {get} /api/todos Get all todos
 * @apiName Get Todos
 * @apiGroup Todos
 *
 *
 * @apiSuccess {Boolean} completed Is the todo item completed or not.
 * @apiSuccess {String} _id  Unique mongo autogenerated id.
 * @apiSuccess {String} name name of the todo.
 * @apiSuccess {Date} completed_date date of todo creation.
 *
 *
 * @apiSuccessExample Success-Response:
 *  {
 *     "completed": false,
 *     "_id": "5c6952accaabf50ea7c583e6",
 *     "name": "Wake up",
 *     "completed_date": "2019-02-17T12:25:16.532Z",
 *     "__v": 0
 *   }
 */
.post(helpers.createTodo)
/**
 * @api {post} /api/todos Create new todo
 * @apiName Create Todo
 * @apiGroup Todos
 *
 *
 * @apiParam {name} name of the todo item
 *
 *
 * @apiSuccess {Boolean} completed Is the todo item completed or not.
 * @apiSuccess {String} _id  Unique mongo autogenerated id.
 * @apiSuccess {String} name name of the newly created todo.
 * @apiSuccess {Date} completed_date date of todo creation.
 *
 *
 * @apiSuccessExample Success-Response:
 *  {
 *     "completed": false,
 *     "_id": "5c6952accaabf50ea7c583e6",
 *     "name": "Wake up",
 *     "completed_date": "2019-02-17T12:25:16.532Z",
 *     "__v": 0
 *   }
 */

router.route("/:todoId")
.get(helpers.showTodo)
/**
 * @api {get} /api/todos/:todoId Show todo
 * @apiName Show Todo
 * @apiGroup Todos
 *
 *
 * @apiSuccess {Boolean} completed Is the todo item completed or not.
 * @apiSuccess {String} _id  Unique mongo autogenerated id.
 * @apiSuccess {String} name name of the todo.
 * @apiSuccess {Date} completed_date date of todo creation.
 *
 *
 * @apiSuccessExample Success-Response:
 *  {
 *     "completed": false,
 *     "_id": "5c6952accaabf50ea7c583e6",
 *     "name": "Wake up",
 *     "completed_date": "2019-02-17T12:25:16.532Z",
 *     "__v": 0
 *   }
 */
.put(helpers.updateTodo)
/**
 * @api {put} /api/todos/:todoId Update todo
 * @apiName Update Todo
 * @apiGroup Todos
 *
 *
 * @apiParam {name} name of the todo item
 *
 *
 * @apiSuccess {Boolean} completed Is the todo item completed or not.
 * @apiSuccess {String} _id  Unique mongo autogenerated id.
 * @apiSuccess {String} name updated name of the todo.
 * @apiSuccess {Date} completed_date date of todo creation.
 *
 *
 * @apiSuccessExample Success-Response:
 *  {
 *     "completed": false,
 *     "_id": "5c6952accaabf50ea7c583e6",
 *     "name": "Go to class",
 *     "completed_date": "2019-02-17T12:25:16.532Z",
 *     "__v": 0
 *   }
 */
.delete(helpers.deleteTodo)
/**
 * @api {delete} /api/todos/:todoId Delete todo
 * @apiName Delete Todo
 * @apiGroup Todos
 *
 *
 * @apiSuccess {String} message simple message to show the succesful deletion.
 *
 *
 * @apiSuccessExample Success-Response:
 *  {
 *     "message": "Todo item deleted succesfully"
 *   }
 */

module.exports = router;
